services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
        - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - moj-prijevoz
  notifications:
    build:
      context: ../
      dockerfile: ../../MojPrijevoz/MojPrijevoz/MojPrijevoz.Notifications/Dockerfile
    env_file:
        - ../MojPrijevoz.WebApi/.env
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RABBITMQ_HOST=rabbitmq    
    container_name: notifications_service
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - moj-prijevoz    

volumes:
  rabbitmq_data:

networks:
  moj-prijevoz:
    driver: bridge