using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MojPrijevoz.Database.Migrations
{
    /// <inheritdoc />
    public partial class VehicleDataSeed : Migration
    {
        private static readonly DateTime _seededAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder) 
        {
            migrationBuilder.InsertData(
                table: "Vehicle",
                columns: new[] { "Id", "Manufacturer", "Model", "NumberOfSeats", "CreatedAt" },
                values: new object[,]
                {
                    { 1, "Alfa Romeo", "145", 5, _seededAt },
                    { 2, "Alfa Romeo", "146", 5, _seededAt },
                    { 3, "Alfa Romeo", "147", 5, _seededAt },
                    { 4, "Alfa Romeo", "156", 5, _seededAt },
                    { 5, "Alfa Romeo", "159", 5, _seededAt },
                    { 6, "Alfa Romeo", "166", 5, _seededAt },
                    { 7, "Alfa Romeo", "GT", 5, _seededAt },
                    { 8, "Alfa Romeo", "GTV", 5, _seededAt },
                    { 9, "Alfa Romeo", "Giulia (952)", 5, _seededAt },
                    { 10, "Alfa Romeo", "Giulietta", 5, _seededAt },
                    { 11, "Alfa Romeo", "MiTo", 5, _seededAt },
                    { 12, "Alfa Romeo", "Stelvio", 5, _seededAt },
                    { 13, "Audi", "A3 8L", 5, _seededAt },
                    { 14, "Audi", "A3 8P", 5, _seededAt },
                    { 15, "Audi", "A3 8V", 5, _seededAt },
                    { 16, "Audi", "A3 8Y", 5, _seededAt },
                    { 17, "Audi", "A4 B5", 5, _seededAt },
                    { 18, "Audi", "A4 B6", 5, _seededAt },
                    { 19, "Audi", "A4 B7", 5, _seededAt },
                    { 20, "Audi", "A4 B8", 5, _seededAt },
                    { 21, "Audi", "A4 B9", 5, _seededAt },
                    { 22, "Audi", "A6 C4", 5, _seededAt },
                    { 23, "Audi", "A6 C5", 5, _seededAt },
                    { 24, "Audi", "A6 C6", 5, _seededAt },
                    { 25, "Audi", "A6 C7", 5, _seededAt },
                    { 26, "Audi", "A6 C8", 5, _seededAt },
                    { 27, "Audi", "Q3", 5, _seededAt },
                    { 28, "Audi", "Q5", 5, _seededAt },
                    { 29, "Audi", "Q7", 5, _seededAt },
                    { 30, "Audi", "Q8", 5, _seededAt },
                    { 31, "BMW", "3 Series E36", 5, _seededAt },
                    { 32, "BMW", "3 Series E46", 5, _seededAt },
                    { 33, "BMW", "3 Series E90", 5, _seededAt },
                    { 34, "BMW", "3 Series F30", 5, _seededAt },
                    { 35, "BMW", "3 Series G20", 5, _seededAt },
                    { 36, "BMW", "5 Series E34", 5, _seededAt },
                    { 37, "BMW", "5 Series E39", 5, _seededAt },
                    { 38, "BMW", "5 Series E60", 5, _seededAt },
                    { 39, "BMW", "5 Series F10", 5, _seededAt },
                    { 40, "BMW", "5 Series G30", 5, _seededAt },
                    { 41, "BMW", "X1 E84", 5, _seededAt },
                    { 42, "BMW", "X1 F48", 5, _seededAt },
                    { 43, "BMW", "X3 E83", 5, _seededAt },
                    { 44, "BMW", "X3 F25", 5, _seededAt },
                    { 45, "BMW", "X3 G01", 5, _seededAt },
                    { 46, "BMW", "X5 E53", 5, _seededAt },
                    { 47, "BMW", "X5 E70", 5, _seededAt },
                    { 48, "BMW", "X5 F15", 5, _seededAt },
                    { 49, "BMW", "X5 G05", 5, _seededAt },
                    { 50, "BMW", "i3", 5, _seededAt },
                    { 51, "Chevrolet/Daewoo", "Aveo T200", 5, _seededAt },
                    { 52, "Chevrolet/Daewoo", "Aveo T300", 5, _seededAt },
                    { 53, "Chevrolet/Daewoo", "Captiva", 5, _seededAt },
                    { 54, "Chevrolet/Daewoo", "Cruze", 5, _seededAt },
                    { 55, "Chevrolet/Daewoo", "Epica", 5, _seededAt },
                    { 56, "Chevrolet/Daewoo", "Kalos", 5, _seededAt },
                    { 57, "Chevrolet/Daewoo", "Lacetti", 5, _seededAt },
                    { 58, "Chevrolet/Daewoo", "Matiz", 5, _seededAt },
                    { 59, "Chevrolet/Daewoo", "Nubira", 5, _seededAt },
                    { 60, "Chevrolet/Daewoo", "Orlando", 7, _seededAt },
                    { 61, "Chevrolet/Daewoo", "Spark", 5, _seededAt },
                    { 62, "Citroën", "Berlingo", 5, _seededAt },
                    { 63, "Citroën", "Berlingo Multispace", 5, _seededAt },
                    { 64, "Citroën", "C-Crosser", 5, _seededAt },
                    { 65, "Citroën", "C-Elysée", 5, _seededAt },
                    { 66, "Citroën", "C1", 5, _seededAt },
                    { 67, "Citroën", "C2", 5, _seededAt },
                    { 68, "Citroën", "C3", 5, _seededAt },
                    { 69, "Citroën", "C3 Aircross", 5, _seededAt },
                    { 70, "Citroën", "C4", 5, _seededAt },
                    { 71, "Citroën", "C4 Cactus", 5, _seededAt },
                    { 72, "Citroën", "C4 Picasso", 7, _seededAt },
                    { 73, "Citroën", "C4 SpaceTourer", 7, _seededAt },
                    { 74, "Citroën", "C5", 5, _seededAt },
                    { 75, "Citroën", "C5 Aircross", 5, _seededAt },
                    { 76, "Citroën", "C8", 7, _seededAt },
                    { 77, "Citroën", "Grand C4 Picasso", 7, _seededAt },
                    { 78, "Citroën", "Jumper", 9, _seededAt },
                    { 79, "Citroën", "Jumpy", 9, _seededAt },
                    { 80, "Citroën", "Xsara", 5, _seededAt },
                    { 81, "Citroën", "Xsara Picasso", 5, _seededAt },
                    { 82, "Citroën", "SpaceTourer", 9, _seededAt },
                    { 83, "Dacia", "Dokker", 5, _seededAt },
                    { 84, "Dacia", "Duster 1", 5, _seededAt },
                    { 85, "Dacia", "Duster 2", 5, _seededAt },
                    { 86, "Dacia", "Jogger", 7, _seededAt },
                    { 87, "Dacia", "Lodgy", 7, _seededAt },
                    { 88, "Dacia", "Logan 1", 5, _seededAt },
                    { 89, "Dacia", "Logan 2", 5, _seededAt },
                    { 90, "Dacia", "Logan MCV", 5, _seededAt },
                    { 91, "Dacia", "Sandero 1", 5, _seededAt },
                    { 92, "Dacia", "Sandero 2", 5, _seededAt },
                    { 93, "Dacia", "Sandero 3", 5, _seededAt },
                    { 94, "Fiat", "500", 5, _seededAt },
                    { 95, "Fiat", "500L", 5, _seededAt },
                    { 96, "Fiat", "500X", 5, _seededAt },
                    { 97, "Fiat", "Bravo 1", 5, _seededAt },
                    { 98, "Fiat", "Bravo 2", 5, _seededAt },
                    { 99, "Fiat", "Croma", 5, _seededAt },
                    { 100, "Fiat", "Doblo", 5, _seededAt },
                    { 101, "Fiat", "Ducato", 9, _seededAt },
                    { 102, "Fiat", "Grande Punto", 5, _seededAt },
                    { 103, "Fiat", "Marea", 5, _seededAt },
                    { 104, "Fiat", "Multipla", 5, _seededAt },
                    { 105, "Fiat", "Panda", 5, _seededAt },
                    { 106, "Fiat", "Punto 1", 5, _seededAt },
                    { 107, "Fiat", "Punto 2", 5, _seededAt },
                    { 108, "Fiat", "Punto 3", 5, _seededAt },
                    { 109, "Fiat", "Scudo", 9, _seededAt },
                    { 110, "Fiat", "Stilo", 5, _seededAt },
                    { 111, "Fiat", "Talento", 9, _seededAt },
                    { 112, "Fiat", "Tempra", 5, _seededAt },
                    { 113, "Fiat", "Tipo", 5, _seededAt },
                    { 114, "Fiat", "Ulysse", 7, _seededAt },
                    { 115, "Ford", "C-Max", 5, _seededAt },
                    { 116, "Ford", "Fiesta Mk5", 5, _seededAt },
                    { 117, "Ford", "Fiesta Mk6", 5, _seededAt },
                    { 118, "Ford", "Fiesta Mk7", 5, _seededAt },
                    { 119, "Ford", "Focus Mk1", 5, _seededAt },
                    { 120, "Ford", "Focus Mk2", 5, _seededAt },
                    { 121, "Ford", "Focus Mk3", 5, _seededAt },
                    { 122, "Ford", "Focus Mk4", 5, _seededAt },
                    { 123, "Ford", "Fusion", 5, _seededAt },
                    { 124, "Ford", "Galaxy", 7, _seededAt },
                    { 125, "Ford", "Ka", 5, _seededAt },
                    { 126, "Ford", "Kuga", 5, _seededAt },
                    { 127, "Ford", "Mondeo Mk3", 5, _seededAt },
                    { 128, "Ford", "Mondeo Mk4", 5, _seededAt },
                    { 129, "Ford", "Mondeo Mk5", 5, _seededAt },
                    { 130, "Ford", "S-Max", 7, _seededAt },
                    { 131, "Ford", "Tourneo Connect", 5, _seededAt },
                    { 132, "Ford", "Tourneo Custom", 9, _seededAt },
                    { 133, "Ford", "Transit", 9, _seededAt },
                    { 134, "Ford", "Transit Connect", 5, _seededAt },
                    { 135, "Ford", "Transit Custom", 9, _seededAt },
                    { 136, "Honda", "Accord 6", 5, _seededAt },
                    { 137, "Honda", "Accord 7", 5, _seededAt },
                    { 138, "Honda", "Accord 8", 5, _seededAt },
                    { 139, "Honda", "CR-V RD", 5, _seededAt },
                    { 140, "Honda", "CR-V RE", 5, _seededAt },
                    { 141, "Honda", "CR-V RW", 5, _seededAt },
                    { 142, "Honda", "Civic EK", 5, _seededAt },
                    { 143, "Honda", "Civic EP", 5, _seededAt },
                    { 144, "Honda", "Civic FK", 5, _seededAt },
                    { 145, "Honda", "Civic FN", 5, _seededAt },
                    { 146, "Hyundai", "Ioniq Electric", 5, _seededAt },
                    { 147, "Hyundai", "Kona Electric", 5, _seededAt },
                    { 148, "Hyundai", "Accent", 5, _seededAt },
                    { 149, "Hyundai", "Elantra", 5, _seededAt },
                    { 150, "Hyundai", "Getz", 5, _seededAt },
                    { 151, "Hyundai", "Kona", 5, _seededAt },
                    { 152, "Hyundai", "Santa Fe", 5, _seededAt },
                    { 153, "Hyundai", "Santa Fe", 7, _seededAt },
                    { 154, "Hyundai", "Sonata", 5, _seededAt },
                    { 155, "Hyundai", "Tucson", 5, _seededAt },
                    { 156, "Hyundai", "i10", 5, _seededAt },
                    { 157, "Hyundai", "i20", 5, _seededAt },
                    { 158, "Hyundai", "i30", 5, _seededAt },
                    { 159, "Hyundai", "i40", 5, _seededAt },
                    { 160, "Hyundai", "ix35", 5, _seededAt },
                    { 161, "Jaguar", "F-Pace", 5, _seededAt },
                    { 162, "Jaguar", "S-Type", 5, _seededAt },
                    { 163, "Jaguar", "X-Type", 5, _seededAt },
                    { 164, "Jaguar", "XE", 5, _seededAt },
                    { 165, "Jaguar", "XF X250", 5, _seededAt },
                    { 166, "Jaguar", "XF X260", 5, _seededAt },
                    { 167, "Kia", "e-Niro", 5, _seededAt },
                    { 168, "Kia", "Carens", 7, _seededAt },
                    { 169, "Kia", "Ceed 1", 5, _seededAt },
                    { 170, "Kia", "Ceed 2", 5, _seededAt },
                    { 171, "Kia", "Ceed 3", 5, _seededAt },
                    { 172, "Kia", "Cerato", 5, _seededAt },
                    { 173, "Kia", "Niro", 5, _seededAt },
                    { 174, "Kia", "Picanto", 5, _seededAt },
                    { 175, "Kia", "Rio 2", 5, _seededAt },
                    { 176, "Kia", "Rio 3", 5, _seededAt },
                    { 177, "Kia", "Rio 4", 5, _seededAt },
                    { 178, "Kia", "Sorento", 7, _seededAt },
                    { 179, "Kia", "Soul", 5, _seededAt },
                    { 180, "Kia", "Sportage 2", 5, _seededAt },
                    { 181, "Kia", "Sportage 3", 5, _seededAt },
                    { 182, "Kia", "Sportage 4", 5, _seededAt },
                    { 183, "Lada", "2101", 5, _seededAt },
                    { 184, "Lada", "2103", 5, _seededAt },
                    { 185, "Lada", "2105", 5, _seededAt },
                    { 186, "Lada", "2107", 5, _seededAt },
                    { 187, "Lada", "Granta", 5, _seededAt },
                    { 188, "Lada", "Kalina", 5, _seededAt },
                    { 189, "Lada", "Niva 4x4", 4, _seededAt },
                    { 190, "Lada", "Priora", 5, _seededAt },
                    { 191, "Lada", "Samara", 5, _seededAt },
                    { 192, "Lada", "Vesta", 5, _seededAt },
                    { 193, "Lancia", "Delta II", 5, _seededAt },
                    { 194, "Lancia", "Kappa", 5, _seededAt },
                    { 195, "Lancia", "Lybra", 5, _seededAt },
                    { 196, "Lancia", "Musa", 5, _seededAt },
                    { 197, "Lancia", "Thesis", 5, _seededAt },
                    { 198, "Lancia", "Ypsilon", 5, _seededAt },
                    { 199, "Land Rover", "Discovery 3", 7, _seededAt },
                    { 200, "Land Rover", "Discovery 4", 7, _seededAt },
                    { 201, "Land Rover", "Discovery Sport", 5, _seededAt },
                    { 202, "Land Rover", "Freelander 1", 5, _seededAt },
                    { 203, "Land Rover", "Freelander 2", 5, _seededAt },
                    { 204, "Land Rover", "Range Rover Evoque", 5, _seededAt },
                    { 205, "Land Rover", "Range Rover L322", 5, _seededAt },
                    { 206, "Land Rover", "Range Rover Sport L320", 5, _seededAt },
                    { 207, "Mazda", "3 BK", 5, _seededAt },
                    { 208, "Mazda", "3 BL", 5, _seededAt },
                    { 209, "Mazda", "3 BM", 5, _seededAt },
                    { 210, "Mazda", "323", 5, _seededAt },
                    { 211, "Mazda", "6 GG", 5, _seededAt },
                    { 212, "Mazda", "6 GH", 5, _seededAt },
                    { 213, "Mazda", "6 GJ", 5, _seededAt },
                    { 214, "Mazda", "CX-3", 5, _seededAt },
                    { 215, "Mazda", "CX-5 KE", 5, _seededAt },
                    { 216, "Mazda", "CX-5 KF", 5, _seededAt },
                    { 217, "Mazda", "CX-7", 5, _seededAt },
                    { 218, "Mazda", "CX-9", 5, _seededAt },
                    { 219, "Mercedes", "R-Class", 7, _seededAt },
                    { 220, "Mercedes", "C-Class W202", 5, _seededAt },
                    { 221, "Mercedes", "C-Class W203", 5, _seededAt },
                    { 222, "Mercedes", "C-Class W204", 5, _seededAt },
                    { 223, "Mercedes", "C-Class W205", 5, _seededAt },
                    { 224, "Mercedes", "C-Class W206", 5, _seededAt },
                    { 225, "Mercedes", "E-Class W210", 5, _seededAt },
                    { 226, "Mercedes", "E-Class W211", 5, _seededAt },
                    { 227, "Mercedes", "E-Class W212", 5, _seededAt },
                    { 228, "Mercedes", "E-Class W213", 5, _seededAt },
                    { 229, "Mercedes", "E-Class W214", 5, _seededAt },
                    { 230, "Mercedes", "GLC", 5, _seededAt },
                    { 231, "Mercedes", "GLE", 5, _seededAt },
                    { 232, "Mercedes", "ML W163", 5, _seededAt },
                    { 233, "Mercedes", "S-Class W220", 5, _seededAt },
                    { 234, "Mercedes", "S-Class W221", 5, _seededAt },
                    { 235, "Mercedes", "S-Class W222", 5, _seededAt },
                    { 236, "Mercedes", "Sprinter W903", 9, _seededAt },
                    { 237, "Mercedes", "Sprinter W906", 9, _seededAt },
                    { 238, "Mercedes", "Sprinter W907", 9, _seededAt },
                    { 239, "Mercedes", "V-Class", 8, _seededAt },
                    { 240, "Mercedes", "Viano", 8, _seededAt },
                    { 241, "Mercedes", "Vito", 8, _seededAt },
                    { 242, "MINI", "Clubman R55", 5, _seededAt },
                    { 243, "MINI", "Cooper F56", 5, _seededAt },
                    { 244, "MINI", "Cooper R50", 5, _seededAt },
                    { 245, "MINI", "Cooper R56", 5, _seededAt },
                    { 246, "MINI", "Countryman F60", 5, _seededAt },
                    { 247, "MINI", "Countryman R60", 5, _seededAt },
                    { 248, "Mitsubishi", "ASX", 5, _seededAt },
                    { 249, "Mitsubishi", "Carisma", 5, _seededAt },
                    { 250, "Mitsubishi", "Colt Z30", 5, _seededAt },
                    { 251, "Mitsubishi", "Galant", 5, _seededAt },
                    { 252, "Mitsubishi", "Lancer 10", 5, _seededAt },
                    { 253, "Mitsubishi", "Lancer 9", 5, _seededAt },
                    { 254, "Mitsubishi", "Outlander 1", 5, _seededAt },
                    { 255, "Mitsubishi", "Outlander 2", 5, _seededAt },
                    { 256, "Mitsubishi", "Outlander 3", 5, _seededAt },
                    { 257, "Mitsubishi", "Outlander 7-seat", 7, _seededAt },
                    { 258, "Mitsubishi", "Pajero II", 7, _seededAt },
                    { 259, "Mitsubishi", "Pajero III", 7, _seededAt },
                    { 260, "Mitsubishi", "Pajero IV", 7, _seededAt },
                    { 261, "Mitsubishi", "Space Star", 5, _seededAt },
                    { 262, "Moskvitch", "2140", 5, _seededAt },
                    { 263, "Nissan", "Leaf ZE0", 5, _seededAt },
                    { 264, "Nissan", "Leaf ZE1", 5, _seededAt },
                    { 265, "Nissan", "Almera N16", 5, _seededAt },
                    { 266, "Nissan", "Juke", 5, _seededAt },
                    { 267, "Nissan", "Micra K11", 5, _seededAt },
                    { 268, "Nissan", "Micra K12", 5, _seededAt },
                    { 269, "Nissan", "Micra K13", 5, _seededAt },
                    { 270, "Nissan", "Navara D22", 5, _seededAt },
                    { 271, "Nissan", "Navara D40", 5, _seededAt },
                    { 272, "Nissan", "Note", 5, _seededAt },
                    { 273, "Nissan", "Pathfinder R51", 7, _seededAt },
                    { 274, "Nissan", "Patrol Y61", 7, _seededAt },
                    { 275, "Nissan", "Primera P11", 5, _seededAt },
                    { 276, "Nissan", "Primera P12", 5, _seededAt },
                    { 277, "Nissan", "Qashqai J10", 5, _seededAt },
                    { 278, "Nissan", "Qashqai J11", 5, _seededAt },
                    { 279, "Nissan", "Qashqai J12", 5, _seededAt },
                    { 280, "Nissan", "Sunny", 5, _seededAt },
                    { 281, "Nissan", "X-Trail T30", 5, _seededAt },
                    { 282, "Nissan", "X-Trail T31", 5, _seededAt },
                    { 283, "Nissan", "X-Trail T32", 5, _seededAt },
                    { 284, "Nissan", "X-Trail T32 7-seat", 7, _seededAt },
                    { 285, "Opel", "Zafira Life", 9, _seededAt },
                    { 286, "Opel", "Astra F", 5, _seededAt },
                    { 287, "Opel", "Astra G", 5, _seededAt },
                    { 288, "Opel", "Astra H", 5, _seededAt },
                    { 289, "Opel", "Astra J", 5, _seededAt },
                    { 290, "Opel", "Astra K", 5, _seededAt },
                    { 291, "Opel", "Corsa B", 5, _seededAt },
                    { 292, "Opel", "Corsa C", 5, _seededAt },
                    { 293, "Opel", "Corsa D", 5, _seededAt },
                    { 294, "Opel", "Corsa E", 5, _seededAt },
                    { 295, "Opel", "Corsa F", 5, _seededAt },
                    { 296, "Opel", "Insignia A", 5, _seededAt },
                    { 297, "Opel", "Insignia B", 5, _seededAt },
                    { 298, "Opel", "Meriva A", 5, _seededAt },
                    { 299, "Opel", "Meriva B", 5, _seededAt },
                    { 300, "Opel", "Movano A", 9, _seededAt },
                    { 301, "Opel", "Movano B", 9, _seededAt },
                    { 302, "Opel", "Vectra A", 5, _seededAt },
                    { 303, "Opel", "Vectra B", 5, _seededAt },
                    { 304, "Opel", "Vectra C", 5, _seededAt },
                    { 305, "Opel", "Vivaro A", 9, _seededAt },
                    { 306, "Opel", "Vivaro B", 9, _seededAt },
                    { 307, "Opel", "Zafira A", 7, _seededAt },
                    { 308, "Opel", "Zafira B", 7, _seededAt },
                    { 309, "Peugeot", "Traveller", 9, _seededAt },
                    { 310, "Peugeot", "106", 4, _seededAt },
                    { 311, "Peugeot", "107", 5, _seededAt },
                    { 312, "Peugeot", "108", 5, _seededAt },
                    { 313, "Peugeot", "2008", 5, _seededAt },
                    { 314, "Peugeot", "205", 5, _seededAt },
                    { 315, "Peugeot", "206", 5, _seededAt },
                    { 316, "Peugeot", "207", 5, _seededAt },
                    { 317, "Peugeot", "208", 5, _seededAt },
                    { 318, "Peugeot", "3008", 5, _seededAt },
                    { 319, "Peugeot", "301", 5, _seededAt },
                    { 320, "Peugeot", "306", 5, _seededAt },
                    { 321, "Peugeot", "307", 5, _seededAt },
                    { 322, "Peugeot", "308", 5, _seededAt },
                    { 323, "Peugeot", "309", 5, _seededAt },
                    { 324, "Peugeot", "405", 5, _seededAt },
                    { 325, "Peugeot", "406", 5, _seededAt },
                    { 326, "Peugeot", "407", 5, _seededAt },
                    { 327, "Peugeot", "408", 5, _seededAt },
                    { 328, "Peugeot", "5008", 7, _seededAt },
                    { 329, "Peugeot", "5008 7-seat", 7, _seededAt },
                    { 330, "Peugeot", "508", 5, _seededAt },
                    { 331, "Peugeot", "Boxer", 9, _seededAt },
                    { 332, "Peugeot", "Expert", 9, _seededAt },
                    { 333, "Peugeot", "Expert Traveller", 9, _seededAt },
                    { 334, "Peugeot", "Partner", 5, _seededAt },
                    { 335, "Peugeot", "Partner Tepee", 5, _seededAt },
                    { 336, "Peugeot", "Rifter", 5, _seededAt },
                    { 337, "Porsche", "Cayenne 955", 5, _seededAt },
                    { 338, "Porsche", "Cayenne 958", 5, _seededAt },
                    { 339, "Porsche", "Macan", 5, _seededAt },
                    { 340, "Porsche", "Panamera 970", 5, _seededAt },
                    { 341, "Porsche", "Panamera 971", 5, _seededAt },
                    { 342, "Renault", "Zoe", 5, _seededAt },
                    { 343, "Renault", "Grand Espace", 9, _seededAt },
                    { 344, "Renault", "Austral", 5, _seededAt },
                    { 345, "Renault", "Captur", 5, _seededAt },
                    { 346, "Renault", "Clio 2", 5, _seededAt },
                    { 347, "Renault", "Clio 3", 5, _seededAt },
                    { 348, "Renault", "Clio 4", 5, _seededAt },
                    { 349, "Renault", "Clio 5", 5, _seededAt },
                    { 350, "Renault", "Espace 3", 7, _seededAt },
                    { 351, "Renault", "Espace 4", 7, _seededAt },
                    { 352, "Renault", "Espace 5", 7, _seededAt },
                    { 353, "Renault", "Grand Scenic", 7, _seededAt },
                    { 354, "Renault", "Kadjar", 5, _seededAt },
                    { 355, "Renault", "Kangoo 1", 5, _seededAt },
                    { 356, "Renault", "Kangoo 2", 5, _seededAt },
                    { 357, "Renault", "Laguna 1", 5, _seededAt },
                    { 358, "Renault", "Laguna 2", 5, _seededAt },
                    { 359, "Renault", "Laguna 3", 5, _seededAt },
                    { 360, "Renault", "Master 2", 9, _seededAt },
                    { 361, "Renault", "Master 3", 9, _seededAt },
                    { 362, "Renault", "Megane 1", 5, _seededAt },
                    { 363, "Renault", "Megane 2", 5, _seededAt },
                    { 364, "Renault", "Megane 3", 5, _seededAt },
                    { 365, "Renault", "Megane 4", 5, _seededAt },
                    { 366, "Renault", "Scenic 1", 7, _seededAt },
                    { 367, "Renault", "Scenic 2", 7, _seededAt },
                    { 368, "Renault", "Scenic 3", 7, _seededAt },
                    { 369, "Renault", "Talisman", 5, _seededAt },
                    { 370, "Renault", "Trafic 2", 9, _seededAt },
                    { 371, "Renault", "Trafic 3", 9, _seededAt },
                    { 372, "Rover", "25", 5, _seededAt },
                    { 373, "Rover", "45", 5, _seededAt },
                    { 374, "Rover", "75", 5, _seededAt },
                    { 375, "Saab", "9-3 NG", 5, _seededAt },
                    { 376, "Saab", "9-3 OG", 5, _seededAt },
                    { 377, "Saab", "9-5", 5, _seededAt },
                    { 378, "Seat", "Alhambra", 7, _seededAt },
                    { 379, "Seat", "Altea", 5, _seededAt },
                    { 380, "Seat", "Arona", 5, _seededAt },
                    { 381, "Seat", "Ateca", 5, _seededAt },
                    { 382, "Seat", "Ibiza 6F", 5, _seededAt },
                    { 383, "Seat", "Ibiza 6J", 5, _seededAt },
                    { 384, "Seat", "Ibiza 6K", 5, _seededAt },
                    { 385, "Seat", "Ibiza 6L", 5, _seededAt },
                    { 386, "Seat", "Leon 1M", 5, _seededAt },
                    { 387, "Seat", "Leon 1P", 5, _seededAt },
                    { 388, "Seat", "Leon 5F", 5, _seededAt },
                    { 389, "Seat", "Leon KL", 5, _seededAt },
                    { 390, "Seat", "Tarraco", 7, _seededAt },
                    { 391, "Seat", "Toledo 1M", 5, _seededAt },
                    { 392, "Seat", "Toledo 5P", 5, _seededAt },
                    { 393, "Smart", "ForFour 454", 4, _seededAt },
                    { 394, "Smart", "ForTwo 450", 2, _seededAt },
                    { 395, "Smart", "ForTwo 451", 2, _seededAt },
                    { 396, "Smart", "ForTwo 453", 2, _seededAt },
                    { 397, "Subaru", "Forester", 5, _seededAt },
                    { 398, "Subaru", "Impreza", 5, _seededAt },
                    { 399, "Subaru", "Legacy", 5, _seededAt },
                    { 400, "Subaru", "Outback", 5, _seededAt },
                    { 401, "Subaru", "XV", 5, _seededAt },
                    { 402, "Suzuki", "Grand Vitara", 5, _seededAt },
                    { 403, "Suzuki", "Ignis", 5, _seededAt },
                    { 404, "Suzuki", "Jimny", 4, _seededAt },
                    { 405, "Suzuki", "SX4", 5, _seededAt },
                    { 406, "Suzuki", "SX4 S-Cross", 5, _seededAt },
                    { 407, "Suzuki", "Swift 2", 5, _seededAt },
                    { 408, "Suzuki", "Swift 3", 5, _seededAt },
                    { 409, "Suzuki", "Swift 4", 5, _seededAt },
                    { 410, "Suzuki", "Vitara", 5, _seededAt },
                    { 411, "Škoda", "Enyaq", 5, _seededAt },
                    { 412, "Škoda", "Fabia 1", 5, _seededAt },
                    { 413, "Škoda", "Fabia 2", 5, _seededAt },
                    { 414, "Škoda", "Fabia 3", 5, _seededAt },
                    { 415, "Škoda", "Fabia 4", 5, _seededAt },
                    { 416, "Škoda", "Kamiq", 5, _seededAt },
                    { 417, "Škoda", "Karoq", 5, _seededAt },
                    { 418, "Škoda", "Kodiaq", 7, _seededAt },
                    { 419, "Škoda", "Kodiaq 7-seat", 7, _seededAt },
                    { 420, "Škoda", "Octavia 1", 5, _seededAt },
                    { 421, "Škoda", "Octavia 2", 5, _seededAt },
                    { 422, "Škoda", "Octavia 3", 5, _seededAt },
                    { 423, "Škoda", "Octavia 4", 5, _seededAt },
                    { 424, "Škoda", "Rapid", 5, _seededAt },
                    { 425, "Škoda", "Roomster", 5, _seededAt },
                    { 426, "Škoda", "Superb 1", 5, _seededAt },
                    { 427, "Škoda", "Superb 2", 5, _seededAt },
                    { 428, "Škoda", "Superb 3", 5, _seededAt },
                    { 429, "Škoda", "Superb 4", 5, _seededAt },
                    { 430, "Tesla", "Model 3", 5, _seededAt },
                    { 431, "Tesla", "Model S", 5, _seededAt },
                    { 432, "Tesla", "Model X", 7, _seededAt },
                    { 433, "Tesla", "Model Y", 5, _seededAt },
                    { 434, "Toyota", "ProAce", 9, _seededAt },
                    { 435, "Toyota", "ProAce Verso", 9, _seededAt },
                    { 436, "Toyota", "Auris 1", 5, _seededAt },
                    { 437, "Toyota", "Auris 2", 5, _seededAt },
                    { 438, "Toyota", "Avensis T22", 5, _seededAt },
                    { 439, "Toyota", "Avensis T25", 5, _seededAt },
                    { 440, "Toyota", "Avensis T27", 5, _seededAt },
                    { 441, "Toyota", "Camry XV40", 5, _seededAt },
                    { 442, "Toyota", "Camry XV50", 5, _seededAt },
                    { 443, "Toyota", "Corolla E11", 5, _seededAt },
                    { 444, "Toyota", "Corolla E12", 5, _seededAt },
                    { 445, "Toyota", "Corolla E15", 5, _seededAt },
                    { 446, "Toyota", "Corolla E18", 5, _seededAt },
                    { 447, "Toyota", "Highlander XU40", 7, _seededAt },
                    { 448, "Toyota", "Land Cruiser J120", 7, _seededAt },
                    { 449, "Toyota", "Land Cruiser J150", 7, _seededAt },
                    { 450, "Toyota", "Land Cruiser J200", 7, _seededAt },
                    { 451, "Toyota", "Land Cruiser J90", 5, _seededAt },
                    { 452, "Toyota", "RAV4 XA20", 5, _seededAt },
                    { 453, "Toyota", "RAV4 XA30", 5, _seededAt },
                    { 454, "Toyota", "RAV4 XA40", 5, _seededAt },
                    { 455, "Toyota", "RAV4 XA50", 5, _seededAt },
                    { 456, "Toyota", "Verso", 7, _seededAt },
                    { 457, "Toyota", "Yaris P1", 5, _seededAt },
                    { 458, "Toyota", "Yaris XP13", 5, _seededAt },
                    { 459, "Toyota", "Yaris XP21", 5, _seededAt },
                    { 460, "Toyota", "Yaris XP9", 5, _seededAt },
                    { 461, "Trabant", "601", 4, _seededAt },
                    { 462, "Volkswagen", "ID.3", 5, _seededAt },
                    { 463, "Volkswagen", "ID.4", 5, _seededAt },
                    { 464, "Volkswagen", "Multivan T5", 9, _seededAt },
                    { 465, "Volkswagen", "Multivan T6", 9, _seededAt },
                    { 466, "Volkswagen", "Caddy", 5, _seededAt },
                    { 467, "Volkswagen", "Crafter", 9, _seededAt },
                    { 468, "Volkswagen", "Golf 1", 5, _seededAt },
                    { 469, "Volkswagen", "Golf 2", 5, _seededAt },
                    { 470, "Volkswagen", "Golf 3", 5, _seededAt },
                    { 471, "Volkswagen", "Golf 4", 5, _seededAt },
                    { 472, "Volkswagen", "Golf 5", 5, _seededAt },
                    { 473, "Volkswagen", "Golf 6", 5, _seededAt },
                    { 474, "Volkswagen", "Golf 7", 5, _seededAt },
                    { 475, "Volkswagen", "Golf 8", 5, _seededAt },
                    { 476, "Volkswagen", "Passat B1", 5, _seededAt },
                    { 477, "Volkswagen", "Passat B2", 5, _seededAt },
                    { 478, "Volkswagen", "Passat B3", 5, _seededAt },
                    { 479, "Volkswagen", "Passat B4", 5, _seededAt },
                    { 480, "Volkswagen", "Passat B5", 5, _seededAt },
                    { 481, "Volkswagen", "Passat B6", 5, _seededAt },
                    { 482, "Volkswagen", "Passat B7", 5, _seededAt },
                    { 483, "Volkswagen", "Passat B8", 5, _seededAt },
                    { 484, "Volkswagen", "Polo 6N", 5, _seededAt },
                    { 485, "Volkswagen", "Polo 6R", 5, _seededAt },
                    { 486, "Volkswagen", "Polo 9N", 5, _seededAt },
                    { 487, "Volkswagen", "Polo AW", 5, _seededAt },
                    { 488, "Volkswagen", "Sharan", 7, _seededAt },
                    { 489, "Volkswagen", "T-Cross", 5, _seededAt },
                    { 490, "Volkswagen", "T-Roc", 5, _seededAt },
                    { 491, "Volkswagen", "T3", 5, _seededAt },
                    { 492, "Volkswagen", "T4", 9, _seededAt },
                    { 493, "Volkswagen", "T5", 9, _seededAt },
                    { 494, "Volkswagen", "T6", 9, _seededAt },
                    { 495, "Volkswagen", "T7", 9, _seededAt },
                    { 496, "Volkswagen", "Tiguan", 5, _seededAt },
                    { 497, "Volkswagen", "Tiguan Allspace", 7, _seededAt },
                    { 498, "Volkswagen", "Touareg", 5, _seededAt },
                    { 499, "Volkswagen", "Touran", 7, _seededAt },
                    { 500, "Volkswagen", "up!", 4, _seededAt },
                    { 501, "Volvo", "850", 5, _seededAt },
                    { 502, "Volvo", "S40 I", 5, _seededAt },
                    { 503, "Volvo", "S60 I", 5, _seededAt },
                    { 504, "Volvo", "S60 II", 5, _seededAt },
                    { 505, "Volvo", "V40 I", 5, _seededAt },
                    { 506, "Volvo", "V60 I", 5, _seededAt },
                    { 507, "Volvo", "V70 I", 5, _seededAt },
                    { 508, "Volvo", "V70 II", 5, _seededAt },
                    { 509, "Volvo", "XC60 I", 5, _seededAt },
                    { 510, "Volvo", "XC60 II", 5, _seededAt },
                    { 511, "Volvo", "XC90 I", 7, _seededAt },
                    { 512, "Volvo", "XC90 II", 7, _seededAt },
                    { 513, "Wartburg", "1.3", 5, _seededAt },
                    { 514, "Wartburg", "353", 5, _seededAt },
                    { 515, "Zastava/Yugo", "101", 5, _seededAt },
                    { 516, "Zastava/Yugo", "128", 5, _seededAt },
                    { 517, "Zastava/Yugo", "750", 4, _seededAt },
                    { 518, "Zastava/Yugo", "Florida", 5, _seededAt },
                    { 519, "Zastava/Yugo", "Skala", 5, _seededAt },
                    { 520, "Zastava/Yugo", "Yugo 45", 5, _seededAt },
                    { 521, "Zastava/Yugo", "Yugo 55", 5, _seededAt },
                    { 522, "Zastava/Yugo", "Yugo Tempo", 5, _seededAt },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder) {
            migrationBuilder.DeleteData(
                table: "Vehicle",
                keyColumn: "Id",
                keyValues: Enumerable.Range(1, 522).Cast<object>().ToArray());
        }
    }
}
