// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MojPrijevoz.Database;

#nullable disable

namespace MojPrijevoz.Database.Migrations
{
    [DbContext(typeof(MojPrijevozDbContext))]
    [Migration("20260412193822_FareDataAdd")]
    partial class FareDataAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MojPrijevoz.Database.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("char(44)")
                        .IsFixedLength();

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("char(24)")
                        .IsFixedLength();

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MojPrijevoz.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7725",
                            Long = "17.1925",
                            Name = "Banja Luka"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.4000",
                            Long = "18.5333",
                            Name = "Banovići"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.8167",
                            Long = "15.8667",
                            Name = "Bihać"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7569",
                            Long = "19.2161",
                            Name = "Bijeljina"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "42.8667",
                            Long = "18.4333",
                            Name = "Bileća"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.8833",
                            Long = "16.1500",
                            Name = "Bosanska Krupa"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1839",
                            Long = "19.3308",
                            Name = "Bratunac"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.0167",
                            Long = "18.2611",
                            Name = "Breza"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.8772",
                            Long = "18.8111",
                            Name = "Brčko"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "45.1333",
                            Long = "17.9833",
                            Name = "Brod"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.0500",
                            Long = "17.4500",
                            Name = "Bugojno"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1000",
                            Long = "17.8833",
                            Name = "Busovača"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.9667",
                            Long = "15.9333",
                            Name = "Cazin"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.1118",
                            Long = "17.7055",
                            Name = "Čapljina"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7167",
                            Long = "18.8167",
                            Name = "Čelić"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.2000",
                            Long = "17.7000",
                            Name = "Čitluk"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.9775",
                            Long = "17.9075",
                            Name = "Derventa"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7314",
                            Long = "18.0844",
                            Name = "Doboj"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1311",
                            Long = "18.0972",
                            Name = "Donji Kakanj"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1500",
                            Long = "17.4000",
                            Name = "Donji Vakuf"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.5064",
                            Long = "18.7747",
                            Name = "Foča"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9667",
                            Long = "17.9000",
                            Name = "Fojnica"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.1667",
                            Long = "18.5333",
                            Name = "Gacko"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.6667",
                            Long = "18.9833",
                            Name = "Goražde"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9333",
                            Long = "17.5833",
                            Name = "Gornji Vakuf"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.8789",
                            Long = "18.4258",
                            Name = "Gradačac"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "45.1458",
                            Long = "17.2539",
                            Name = "Gradiška"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.6892",
                            Long = "18.3022",
                            Name = "Gračanica"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8217",
                            Long = "18.2017",
                            Name = "Hadžići"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8167",
                            Long = "18.3000",
                            Name = "Ilidža"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9500",
                            Long = "18.2667",
                            Name = "Ilijaš"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.6500",
                            Long = "17.7500",
                            Name = "Jablanica"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.3417",
                            Long = "17.2694",
                            Name = "Jajce"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9431",
                            Long = "18.0775",
                            Name = "Kiseljak"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.2256",
                            Long = "18.6925",
                            Name = "Kladanj"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.5333",
                            Long = "16.7667",
                            Name = "Ključ"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8253",
                            Long = "17.0058",
                            Name = "Livno"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.6361",
                            Long = "18.8444",
                            Name = "Lopare"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.5500",
                            Long = "18.5167",
                            Name = "Lukavac"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.1981",
                            Long = "17.5467",
                            Name = "Ljubuški"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.5500",
                            Long = "18.1000",
                            Name = "Maglaj"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1661",
                            Long = "19.0750",
                            Name = "Milići"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.3436",
                            Long = "17.8075",
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "45.0481",
                            Long = "16.3769",
                            Name = "Novi Grad"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1748",
                            Long = "17.6634",
                            Name = "Novi Travnik"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "45.0106",
                            Long = "18.3264",
                            Name = "Odžak"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1275",
                            Long = "18.5800",
                            Name = "Olovo"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "45.0361",
                            Long = "18.6933",
                            Name = "Orašje"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8119",
                            Long = "18.5711",
                            Name = "Pale"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.4720",
                            Long = "17.3297",
                            Name = "Posušje"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.9808",
                            Long = "16.7133",
                            Name = "Prijedor"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.7986",
                            Long = "19.0036",
                            Name = "Rogatica"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7667",
                            Long = "16.6667",
                            Name = "Sanski Most"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.4917",
                            Long = "19.0028",
                            Name = "Sapna"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8564",
                            Long = "18.4131",
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1042",
                            Long = "19.2972",
                            Name = "Srebrenica"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.7000",
                            Long = "18.4833",
                            Name = "Srebrenik"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.8667",
                            Long = "18.4333",
                            Name = "Stara Gora"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.0825",
                            Long = "17.9558",
                            Name = "Stolac"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.3831",
                            Long = "17.5927",
                            Name = "Široki Brijeg"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.6142",
                            Long = "17.9894",
                            Name = "Tešanj"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.2264",
                            Long = "17.6597",
                            Name = "Travnik"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "42.7119",
                            Long = "18.3461",
                            Name = "Trebinje"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.5381",
                            Long = "18.6761",
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1619",
                            Long = "18.3269",
                            Name = "Vareš"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9833",
                            Long = "18.1667",
                            Name = "Visoko"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1585",
                            Long = "17.7885",
                            Name = "Vitez"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.1833",
                            Long = "18.9333",
                            Name = "Vlasenica"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "43.9000",
                            Long = "18.3500",
                            Name = "Vogošća"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.3842",
                            Long = "19.1025",
                            Name = "Zvornik"
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.4333",
                            Long = "18.0333",
                            Name = "Žepče"
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lat = "44.4500",
                            Long = "18.6500",
                            Name = "Živinice"
                        });
                });

            modelBuilder.Entity("MojPrijevoz.Database.DriversDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<float?>("MaxKm")
                        .HasColumnType("real");

                    b.Property<float>("MinKm")
                        .HasColumnType("real");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("DriversDiscount", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("FareDataId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("FareDataId")
                        .IsUnique();

                    b.HasIndex("PassengerId");

                    b.ToTable("Fare", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.FareData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationLat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DestinationLong")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("FareDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OriginCityId");

                    b.ToTable("FareData", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.FareOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AdditionalPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FareDataId")
                        .HasColumnType("int");

                    b.Property<int?>("LastOfferId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<short>("Side")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("UserVehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FareDataId");

                    b.HasIndex("LastOfferId");

                    b.HasIndex("UserVehicleId");

                    b.ToTable("FareOffer", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FareId")
                        .HasColumnType("int");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.HasIndex("FareId", "FromId", "ToId")
                        .IsUnique();

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.StopPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FareDataId")
                        .HasColumnType("int");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FareDataId", "Order")
                        .IsUnique();

                    b.ToTable("StopPoint", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FareId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("Side")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FareId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfFares")
                        .HasColumnType("int");

                    b.Property<short>("ProfileType")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProfileType")
                        .IsUnique();

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("FuelConsumption")
                        .HasColumnType("real");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<float>("PricePerKm")
                        .HasColumnType("real");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ProfileId", "VehicleId", "ModelYear")
                        .IsUnique();

                    b.ToTable("UserVehicle", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.Administrator", b =>
                {
                    b.HasBaseType("MojPrijevoz.Database.Account");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.User", b =>
                {
                    b.HasBaseType("MojPrijevoz.Database.Account");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<string>("Picture")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasIndex("CityId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MojPrijevoz.Database.DriversDiscount", b =>
                {
                    b.HasOne("MojPrijevoz.Database.UserProfile", "Profile")
                        .WithMany("DriversDiscounts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Fare", b =>
                {
                    b.HasOne("MojPrijevoz.Database.UserProfile", "Driver")
                        .WithMany("FareDrivers")
                        .HasForeignKey("DriverId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.FareData", "FareData")
                        .WithOne("Fare")
                        .HasForeignKey("MojPrijevoz.Database.Fare", "FareDataId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.UserProfile", "Passenger")
                        .WithMany("FarePassengers")
                        .HasForeignKey("PassengerId")
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FareData");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("MojPrijevoz.Database.FareData", b =>
                {
                    b.HasOne("MojPrijevoz.Database.City", "OriginCity")
                        .WithMany("FareDataOriginCities")
                        .HasForeignKey("OriginCityId")
                        .IsRequired();

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("MojPrijevoz.Database.FareOffer", b =>
                {
                    b.HasOne("MojPrijevoz.Database.FareData", "FareData")
                        .WithMany("FareOffers")
                        .HasForeignKey("FareDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.FareOffer", "LastOffer")
                        .WithMany()
                        .HasForeignKey("LastOfferId");

                    b.HasOne("MojPrijevoz.Database.UserVehicle", "UserVehicle")
                        .WithMany("FareOffers")
                        .HasForeignKey("UserVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FareData");

                    b.Navigation("LastOffer");

                    b.Navigation("UserVehicle");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Rating", b =>
                {
                    b.HasOne("MojPrijevoz.Database.Fare", "Fare")
                        .WithMany("Ratings")
                        .HasForeignKey("FareId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.UserProfile", "From")
                        .WithMany("RatingFroms")
                        .HasForeignKey("FromId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.UserProfile", "To")
                        .WithMany("RatingTos")
                        .HasForeignKey("ToId")
                        .IsRequired();

                    b.Navigation("Fare");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("MojPrijevoz.Database.StopPoint", b =>
                {
                    b.HasOne("MojPrijevoz.Database.FareData", "FareData")
                        .WithMany("StopPoints")
                        .HasForeignKey("FareDataId")
                        .IsRequired();

                    b.Navigation("FareData");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Transaction", b =>
                {
                    b.HasOne("MojPrijevoz.Database.Fare", "Fare")
                        .WithMany("Transactions")
                        .HasForeignKey("FareId")
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserProfile", b =>
                {
                    b.HasOne("MojPrijevoz.Database.User", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserVehicle", b =>
                {
                    b.HasOne("MojPrijevoz.Database.UserProfile", "Profile")
                        .WithMany("UserVehicles")
                        .HasForeignKey("ProfileId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.Vehicle", "Vehicle")
                        .WithMany("UserVehicles")
                        .HasForeignKey("VehicleId")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Administrator", b =>
                {
                    b.HasOne("MojPrijevoz.Database.Account", null)
                        .WithOne()
                        .HasForeignKey("MojPrijevoz.Database.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MojPrijevoz.Database.User", b =>
                {
                    b.HasOne("MojPrijevoz.Database.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .IsRequired();

                    b.HasOne("MojPrijevoz.Database.Account", null)
                        .WithOne()
                        .HasForeignKey("MojPrijevoz.Database.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MojPrijevoz.Database.City", b =>
                {
                    b.Navigation("FareDataOriginCities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Fare", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MojPrijevoz.Database.FareData", b =>
                {
                    b.Navigation("Fare");

                    b.Navigation("FareOffers");

                    b.Navigation("StopPoints");
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserProfile", b =>
                {
                    b.Navigation("DriversDiscounts");

                    b.Navigation("FareDrivers");

                    b.Navigation("FarePassengers");

                    b.Navigation("RatingFroms");

                    b.Navigation("RatingTos");

                    b.Navigation("UserVehicles");
                });

            modelBuilder.Entity("MojPrijevoz.Database.UserVehicle", b =>
                {
                    b.Navigation("FareOffers");
                });

            modelBuilder.Entity("MojPrijevoz.Database.Vehicle", b =>
                {
                    b.Navigation("UserVehicles");
                });

            modelBuilder.Entity("MojPrijevoz.Database.User", b =>
                {
                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
